# SwiftLint configuration for FireworksClicker
# Game development oriented - relaxed on some strict rules

# Paths to exclude from linting
excluded:
  - build
  - DerivedData
  - .build
  - Pods
  - Carthage
  - vendor
  - "*.generated.swift"

# Disable overly strict rules for game development
disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - identifier_name
  - large_tuple

# Enable good practice rules as warnings
opt_in_rules:
  - force_unwrapping
  - empty_count
  - empty_string
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Configure force_cast and force_try as warnings (not errors)
force_cast: warning
force_try: warning

# Trailing whitespace configuration
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

# Vertical whitespace configuration
vertical_whitespace:
  max_empty_lines: 2

# Trailing comma configuration - allow trailing commas to match swift-format
trailing_comma:
  mandatory_comma: true

# Reporter type (xcode for IDE integration)
reporter: xcode
